version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - TZ=GMT+6
      - PGTZ=GMT+6
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hospital
    ports:
      - "5432:5432"