rest:
  host: 0.0.0.0
  port: 8000

database:
  dsn: "host=localhost port=5432 user=postgres password=secret dbname=hospital sslmode=disable"
  url: "postgres://postgres:secret@localhost:5432/hospital?sslmode=disable"