DROP TABLE IF EXISTS "public.record";
DROP TABLE IF EXISTS "public.specialize";
DROP TABLE IF EXISTS "public.doctor";
DROP TABLE IF EXISTS "public.public_servant";
DROP TABLE IF EXISTS "public.users";
DROP TABLE IF EXISTS "public.discover";
DROP TABLE IF EXISTS "public.disease";
DROP TABLE IF EXISTS "public.country";
DROP TABLE IF EXISTS "public.disease_type";